name: Testing
on: push

jobs:
  test_this:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting environment 1
      run:
        apt-get install -y python-setuptools
    - name: Setting environment 2
      run:
        pip3 install --user django
    - name: Run Django unit tests 
      run:
        cd airline0
        python3 manage.py test
