name: Testing
on: push

jobs:
  test_this:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests 123
      run:
        apt-get install -y python-setuptools
        cd airline0
        pip3 install --user django
        python3 manage.py test
